name = "visitor-management-customer-fe"
type = "javascript"
main = "dist"

[env.production]
routes = [
  { pattern = "*.larkvel.com/*", zone_name = "larkvel.com" }
]
vars = { VITE_API_BASE_URL = "https://api-visit.larkvel.com" }

[build]
command = "npm run build"
cwd = "."